[package]
name = "LogQuest"
version = "0.1.0"
description = "A Deluxe Toolbox for EverQuest enjoyers"
authors = ["Tinkering Guild"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "shell-open", "global-shortcut"] }
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["cargo"] }
serde_json = "1"
xml-rs = "0.8.20"
anyhow = "1.0.86"
zip = {version="2.1.3", default-features = false, features = ["deflate"] }
dirs = "5.0.1"
toml = "0.8.14"



[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
